site_name: NodeMCU Documentation
site_description: Description of the NodeMCU documentation
repo_url: https://github.com/nodemcu/nodemcu-firmware/

theme: readthedocs
strict: false

markdown_extensions:
#http://pythonhosted.org/Markdown/extensions/admonition.html
- admonition:
- toc:
    permalink: True

#requird due to https://github.com/rtfd/readthedocs.org/issues/1313
#see http://mkdocs.readthedocs.org/en/latest/user-guide/styling-your-docs/#customising-a-theme
extra_css:
- css/extra.css
extra_javascript:
- js/extra.js

pages:
- Overview: 'index.md'
- Basics:
    - Building the firmware: 'build.md'
    - Flashing the firmware: 'flash.md'
    - Uploading code: 'upload.md'
    - Support: 'support.md'
- FAQs:
    - Lua Developer FAQ: 'lua-developer-faq.md'
    - Extension Developer FAQ: 'extn-developer-faq.md'
    - Hardware FAQ: 'hardware-faq.md'
- Whitepapers:
    - Filesystem on SD card: 'sdcard.md'
    - Internal filesystem: 'spiffs.md' 
- Modules:
    - 'adc': 'modules/adc.md'
    - 'adxl345': 'modules/adxl345.md'
    - 'am2320': 'modules/am2320.md'
    - 'apa102': 'modules/apa102.md'
    - 'bit': 'modules/bit.md'
    - 'bme280': 'modules/bme280.md'
    - 'bmp085': 'modules/bmp085.md'
    - 'cjson': 'modules/cjson.md'
    - 'coap': 'modules/coap.md'
    - 'crypto': 'modules/crypto.md'
    - 'dht': 'modules/dht.md'
    - 'encoder': 'modules/encoder.md'
    - 'enduser setup': 'modules/enduser-setup.md'
    - 'file': 'modules/file.md'
    - 'gdbstub': 'modules/gdbstub.md'
    - 'gpio': 'modules/gpio.md'
    - 'hmc5883l': 'modules/hmc5883l.md'
    - 'http': 'modules/http.md'
    - 'hx711' : 'modules/hx711.md'
    - 'i2c' : 'modules/i2c.md'
    - 'l3g4200d' : 'modules/l3g4200d.md'
    - 'mdns': 'modules/mdns.md'
    - 'mqtt': 'modules/mqtt.md'
    - 'net': 'modules/net.md'
    - 'node': 'modules/node.md'
    - 'ow (1-Wire)': 'modules/ow.md'
    - 'pcm' : 'modules/pcm.md'
    - 'perf': 'modules/perf.md'
    - 'pwm' : 'modules/pwm.md'
    - 'rc' : 'modules/rc.md'
    - 'rfswitch' : 'modules/rfswitch.md'
    - 'rotary' : 'modules/rotary.md'
    - 'rtcfifo': 'modules/rtcfifo.md'
    - 'rtcmem': 'modules/rtcmem.md'
    - 'rtctime': 'modules/rtctime.md'
    - 'sigma delta': 'modules/sigma-delta.md'
    - 'sntp': 'modules/sntp.md'
    - 'somfy': 'modules/somfy.md'
    - 'spi': 'modules/spi.md'
    - 'struct': 'modules/struct.md'
    - 'switec': 'modules/switec.md'
    - 'tm1829': 'modules/tm1829.md'
    - 'tmr': 'modules/tmr.md'
    - 'tsl2561': 'modules/tsl2561.md'
    - 'u8g': 'modules/u8g.md'
    - 'uart': 'modules/uart.md'
    - 'ucg': 'modules/ucg.md'
    - 'websocket': 'modules/websocket.md'
    - 'wifi': 'modules/wifi.md'
    - 'ws2801': 'modules/ws2801.md'
    - 'ws2812': 'modules/ws2812.md'
